spring.application.name=reboot-app

#CassandraOriginal
# Cassandra
#spring.data.cassandra.keyspace-name=reboot_app
#spring.data.cassandra.port=9042
#spring.data.cassandra.contact-points=localhost
#spring.data.cassandra.schema-action=create_if_not_exists



# Cassandra_OLD
#spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
#spring.cassandra.request.timeout=10s
#spring.cassandra.connection.connect-timeout=10s
#spring.cassandra.connection.init-query-timeout=10s
#spring.cassandra.local-datacenter=datacenter1
#spring.cassandra.keyspace-name=reboot_app

#spring.data.cassandra.schema-action=CREATE_IF_NOT_EXISTS
#spring.data.cassandra.port=9042
#spring.data.cassandra.contact-points=localhost

# Cassandra_NEW_1
#spring.data.cassandra.schema-action=CREATE_IF_NOT_EXISTS
#spring.data.cassandra.connect-timeout-millis=10000
#spring.data.cassandra.read-timeout-millis=10000
#spring.data.cassandra.connect-timeout=10000ms
#spring.data.cassandra.read-timeout=10000ms
#spring.data.cassandra.pool.pool-timeout=10000ms
#spring.cassandra.local-datacenter=datacenter1
#spring.data.cassandra.port=9042
#spring.data.cassandra.contact-points=localhost
#spring.data.cassandra.keyspace-name=reboot_app
#spring.data.cassandra.username=cassandra
#spring.data.cassandra.password=cassandra


# Cassandra_NEW_2
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
spring.cassandra.connect-timeout-millis=10000
spring.cassandra.read-timeout-millis=10000
spring.cassandra.connect-timeout=10000ms
spring.cassandra.read-timeout=10000ms
spring.cassandra.pool.pool-timeout=10000ms
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.port=9042
spring.cassandra.contact-points=localhost
spring.cassandra.keyspace-name=reboot_app
spring.cassandra.username=cassandra
spring.cassandra.password=cassandra


# Actuator
management.endpoints.web.exposure.include=health
management.health.cassandra.enabled=true